name: Deploy to Server

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER2KEY }}

    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.HOST2 }}
        username: ubuntu
        key: ${{ secrets.SERVER2KEY }}
        source: "."
        target: "/var/www/myapp"

    - name: Run deployment commands
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST2 }}
        username: ubuntu
        key: ${{ secrets.SERVER2KEY }}
        script: |
          cd /var/www/myapp
          npm install
          pm2 restart all
